//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_SMARTEntities1 : DbContext
    {
        public DB_SMARTEntities1()
            : base("name=DB_SMARTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<emlNotification> emlNotifications { get; set; }
        public virtual DbSet<emlNotificationLog> emlNotificationLogs { get; set; }
        public virtual DbSet<emlTemplate> emlTemplates { get; set; }
        public virtual DbSet<mstContact> mstContacts { get; set; }
        public virtual DbSet<mstContact_ARC> mstContact_ARC { get; set; }
        public virtual DbSet<mstEmailPool> mstEmailPools { get; set; }
        public virtual DbSet<mstKecamatan> mstKecamatans { get; set; }
        public virtual DbSet<mstPengumuman> mstPengumumen { get; set; }
        public virtual DbSet<mstReference> mstReferences { get; set; }
        public virtual DbSet<mstRegionAdmin> mstRegionAdmins { get; set; }
        public virtual DbSet<mstRekanan> mstRekanans { get; set; }
        public virtual DbSet<mstRekanan_ARC> mstRekanan_ARC { get; set; }
        public virtual DbSet<mstScoreValue> mstScoreValues { get; set; }
        public virtual DbSet<mstSegmentasi> mstSegmentasis { get; set; }
        public virtual DbSet<mstSubRegion> mstSubRegions { get; set; }
        public virtual DbSet<mstTemplateDokRekanan> mstTemplateDokRekanans { get; set; }
        public virtual DbSet<mstTypeOfBadanUsaha> mstTypeOfBadanUsahas { get; set; }
        public virtual DbSet<mstTypeOfDocument> mstTypeOfDocuments { get; set; }
        public virtual DbSet<mstTypeOfRegion> mstTypeOfRegions { get; set; }
        public virtual DbSet<mstTypeOfRekanan> mstTypeOfRekanans { get; set; }
        public virtual DbSet<mstWilayah> mstWilayahs { get; set; }
        public virtual DbSet<rptKAP> rptKAPs { get; set; }
        public virtual DbSet<rptKJPP> rptKJPPs { get; set; }
        public virtual DbSet<rptKonsultanManageman> rptKonsultanManagemen { get; set; }
        public virtual DbSet<rptNotari> rptNotaris { get; set; }
        public virtual DbSet<trxAsisten> trxAsistens { get; set; }
        public virtual DbSet<trxAuditLog> trxAuditLogs { get; set; }
        public virtual DbSet<trxBranchOffice> trxBranchOffices { get; set; }
        public virtual DbSet<trxBranchOffice_ARC> trxBranchOffice_ARC { get; set; }
        public virtual DbSet<trxBranchOfficeHeader> trxBranchOfficeHeaders { get; set; }
        public virtual DbSet<trxBranchOfficeTMP> trxBranchOfficeTMPs { get; set; }
        public virtual DbSet<trxDataOrganisasi> trxDataOrganisasis { get; set; }
        public virtual DbSet<trxDataOrganisasi_ARC> trxDataOrganisasi_ARC { get; set; }
        public virtual DbSet<trxDetailPekerjaan> trxDetailPekerjaans { get; set; }
        public virtual DbSet<trxDetailPekerjaan_ARC> trxDetailPekerjaan_ARC { get; set; }
        public virtual DbSet<trxDetailPekerjaanAS_3M> trxDetailPekerjaanAS_3M { get; set; }
        public virtual DbSet<trxDetailPekerjaanBLG> trxDetailPekerjaanBLGs { get; set; }
        public virtual DbSet<trxDetailPekerjaanHeader> trxDetailPekerjaanHeaders { get; set; }
        public virtual DbSet<trxDetailPekerjaanTMP> trxDetailPekerjaanTMPs { get; set; }
        public virtual DbSet<trxDocMandatoryDetail> trxDocMandatoryDetails { get; set; }
        public virtual DbSet<trxDocMandatoryFile> trxDocMandatoryFiles { get; set; }
        public virtual DbSet<trxDocumentMandatory> trxDocumentMandatories { get; set; }
        public virtual DbSet<trxFileDataPekerjaan> trxFileDataPekerjaans { get; set; }
        public virtual DbSet<trxManagementBlackListHistory> trxManagementBlackListHistories { get; set; }
        public virtual DbSet<trxMonitoringFeeBased> trxMonitoringFeeBaseds { get; set; }
        public virtual DbSet<trxMonitoringFeeBased_ARC> trxMonitoringFeeBased_ARC { get; set; }
        public virtual DbSet<trxNotari> trxNotaris { get; set; }
        public virtual DbSet<trxNotaris_ARC> trxNotaris_ARC { get; set; }
        public virtual DbSet<trxNotarisDetail> trxNotarisDetails { get; set; }
        public virtual DbSet<trxNotarisTabular> trxNotarisTabulars { get; set; }
        public virtual DbSet<trxNotificationAttachment> trxNotificationAttachments { get; set; }
        public virtual DbSet<trxNotificationContent> trxNotificationContents { get; set; }
        public virtual DbSet<trxNotificationHeader> trxNotificationHeaders { get; set; }
        public virtual DbSet<trxNotificationRecipient> trxNotificationRecipients { get; set; }
        public virtual DbSet<trxOwnership> trxOwnerships { get; set; }
        public virtual DbSet<trxOwnership_ARC> trxOwnership_ARC { get; set; }
        public virtual DbSet<trxRekananDocument> trxRekananDocuments { get; set; }
        public virtual DbSet<trxRekananDocumentTrack> trxRekananDocumentTracks { get; set; }
        public virtual DbSet<trxSanksiEksternal> trxSanksiEksternals { get; set; }
        public virtual DbSet<trxSanksiEksternal_ARC> trxSanksiEksternal_ARC { get; set; }
        public virtual DbSet<trxSanksiInternal> trxSanksiInternals { get; set; }
        public virtual DbSet<trxSanksiInternal_ARC> trxSanksiInternal_ARC { get; set; }
        public virtual DbSet<trxTenagaAhli> trxTenagaAhlis { get; set; }
        public virtual DbSet<trxTenagaAhli_ARC> trxTenagaAhli_ARC { get; set; }
        public virtual DbSet<trxTenagaAhliHeader> trxTenagaAhliHeaders { get; set; }
        public virtual DbSet<trxTenagaAhliTetapImp> trxTenagaAhliTetapImps { get; set; }
        public virtual DbSet<trxTenagaAhliTidakTetap> trxTenagaAhliTidakTetaps { get; set; }
        public virtual DbSet<trxTenagaAhliTidakTetapImp> trxTenagaAhliTidakTetapImps { get; set; }
        public virtual DbSet<trxTenagaAhliTMP> trxTenagaAhliTMPs { get; set; }
        public virtual DbSet<trxTenagaAhliUpload> trxTenagaAhliUploads { get; set; }
        public virtual DbSet<trxTenagaPendukung> trxTenagaPendukungs { get; set; }
        public virtual DbSet<trxTenagaPendukungImp> trxTenagaPendukungImps { get; set; }
        public virtual DbSet<trxTenagaPendukungTMP> trxTenagaPendukungTMPs { get; set; }
        public virtual DbSet<rptAsuransi> rptAsuransis { get; set; }
        public virtual DbSet<rptBalaiLelang> rptBalaiLelangs { get; set; }
        public virtual DbSet<trxDetailPekerjaanAS_Tahunan> trxDetailPekerjaanAS_Tahunan { get; set; }
        public virtual DbSet<trxFileScanned> trxFileScanneds { get; set; }
        public virtual DbSet<vwKelengkapanDokumenRekanan> vwKelengkapanDokumenRekanans { get; set; }
        public virtual DbSet<vwNotarisTabular> vwNotarisTabulars { get; set; }
        public virtual DbSet<vwUserRole> vwUserRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<trxDetailPekerjaanAS_1M> trxDetailPekerjaanAS_1M { get; set; }
        public virtual DbSet<trxDetailPekerjaanAS_1MTMP> trxDetailPekerjaanAS_1MTMP { get; set; }
        public virtual DbSet<trxNotarisItem> trxNotarisItem { get; set; }
        public virtual DbSet<trxManagement> trxManagement { get; set; }
        public virtual DbSet<vwRekManagemenBL> vwRekManagemenBL { get; set; }
        public virtual DbSet<trxManagementP2PK> trxManagementP2PK { get; set; }
        public virtual DbSet<trxNotificationDetail> trxNotificationDetail { get; set; }
        public virtual DbSet<trxRegistrationRequest> trxRegistrationRequest { get; set; }
        public virtual DbSet<mstPertanyaan> mstPertanyaan { get; set; }
        public virtual DbSet<trxPertanyaan> trxPertanyaan { get; set; }
        public virtual DbSet<trxKonsolidasi> trxKonsolidasi { get; set; }
        public virtual DbSet<mstKategoriResiko> mstKategoriResiko { get; set; }
        public virtual DbSet<trxPertanyaanNilai> trxPertanyaanNilai { get; set; }
        public virtual DbSet<vwPertanyaanNilai> vwPertanyaanNilai { get; set; }
        public virtual DbSet<vwPertanyaanNilaiAkhir> vwPertanyaanNilaiAkhir { get; set; }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan")]
        public virtual IQueryable<fDashFeeByRekanan_Result> fDashFeeByRekanan(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan_Bulan")]
        public virtual IQueryable<fDashFeeByRekanan_Bulan_Result> fDashFeeByRekanan_Bulan(Nullable<int> tahun, Nullable<System.Guid> idRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan_Bulan_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan_Bulan](@Tahun, @IdRekanan)", tahunParameter, idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan_Seg")]
        public virtual IQueryable<fDashFeeByRekanan_Seg_Result> fDashFeeByRekanan_Seg(Nullable<int> tahun, Nullable<int> idTypeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan_Seg_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan_Seg](@Tahun, @IdTypeOfRekanan)", tahunParameter, idTypeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan_Seg_Bulan")]
        public virtual IQueryable<fDashFeeByRekanan_Seg_Bulan_Result> fDashFeeByRekanan_Seg_Bulan(Nullable<int> tahun, Nullable<int> idTypeOfRekanan, Nullable<int> idSegmentasi)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            var idSegmentasiParameter = idSegmentasi.HasValue ?
                new ObjectParameter("IdSegmentasi", idSegmentasi) :
                new ObjectParameter("IdSegmentasi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan_Seg_Bulan_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan_Seg_Bulan](@Tahun, @IdTypeOfRekanan, @IdSegmentasi)", tahunParameter, idTypeOfRekananParameter, idSegmentasiParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan1237")]
        public virtual IQueryable<fDashFeeByRekanan1237_Result> fDashFeeByRekanan1237(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan1237_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan1237](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan45")]
        public virtual IQueryable<fDashFeeByRekanan45_Result> fDashFeeByRekanan45(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan45_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan45](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekanan6")]
        public virtual IQueryable<fDashFeeByRekanan6_Result> fDashFeeByRekanan6(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekanan6_Result>("[DB_SMARTEntities1].[fDashFeeByRekanan6](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashNilaiPenutupanByRekanan")]
        public virtual IQueryable<fDashNilaiPenutupanByRekanan_Result> fDashNilaiPenutupanByRekanan(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashNilaiPenutupanByRekanan_Result>("[DB_SMARTEntities1].[fDashNilaiPenutupanByRekanan](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashNilaiPenutupanByRekanan_Bulan")]
        public virtual IQueryable<fDashNilaiPenutupanByRekanan_Bulan_Result> fDashNilaiPenutupanByRekanan_Bulan(Nullable<int> tahun, Nullable<System.Guid> idRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashNilaiPenutupanByRekanan_Bulan_Result>("[DB_SMARTEntities1].[fDashNilaiPenutupanByRekanan_Bulan](@Tahun, @IdRekanan)", tahunParameter, idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashPekerjaanByRekanan")]
        public virtual IQueryable<fDashPekerjaanByRekanan_Result> fDashPekerjaanByRekanan(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashPekerjaanByRekanan_Result>("[DB_SMARTEntities1].[fDashPekerjaanByRekanan](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashPekerjaanByRekanan1237")]
        public virtual IQueryable<fDashPekerjaanByRekanan1237_Result> fDashPekerjaanByRekanan1237(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashPekerjaanByRekanan1237_Result>("[DB_SMARTEntities1].[fDashPekerjaanByRekanan1237](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashPekerjaanByRekanan45")]
        public virtual IQueryable<fDashPekerjaanByRekanan45_Result> fDashPekerjaanByRekanan45(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashPekerjaanByRekanan45_Result>("[DB_SMARTEntities1].[fDashPekerjaanByRekanan45](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashPekerjaanByRekanan6")]
        public virtual IQueryable<fDashPekerjaanByRekanan6_Result> fDashPekerjaanByRekanan6(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashPekerjaanByRekanan6_Result>("[DB_SMARTEntities1].[fDashPekerjaanByRekanan6](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDataOrganisasiByRek")]
        public virtual IQueryable<fDataOrganisasiByRek_Result> fDataOrganisasiByRek(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDataOrganisasiByRek_Result>("[DB_SMARTEntities1].[fDataOrganisasiByRek](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDataOrganisasiByRek1")]
        public virtual IQueryable<fDataOrganisasiByRek1_Result> fDataOrganisasiByRek1(Nullable<System.Guid> idRekanan, Nullable<int> tipeRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var tipeRekananParameter = tipeRekanan.HasValue ?
                new ObjectParameter("TipeRekanan", tipeRekanan) :
                new ObjectParameter("TipeRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDataOrganisasiByRek1_Result>("[DB_SMARTEntities1].[fDataOrganisasiByRek1](@IdRekanan, @TipeRekanan)", idRekananParameter, tipeRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDataRekananByIds")]
        public virtual IQueryable<fDataRekananByIds_Result> fDataRekananByIds(string emailAddress, string nomorNPWP, string nomorKTP)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("emailAddress", emailAddress) :
                new ObjectParameter("emailAddress", typeof(string));
    
            var nomorNPWPParameter = nomorNPWP != null ?
                new ObjectParameter("nomorNPWP", nomorNPWP) :
                new ObjectParameter("nomorNPWP", typeof(string));
    
            var nomorKTPParameter = nomorKTP != null ?
                new ObjectParameter("nomorKTP", nomorKTP) :
                new ObjectParameter("nomorKTP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDataRekananByIds_Result>("[DB_SMARTEntities1].[fDataRekananByIds](@emailAddress, @nomorNPWP, @nomorKTP)", emailAddressParameter, nomorNPWPParameter, nomorKTPParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGenerateUsernamePassword")]
        public virtual IQueryable<fGenerateUsernamePassword_Result> fGenerateUsernamePassword(string idRekanan)
        {
            var idRekananParameter = idRekanan != null ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGenerateUsernamePassword_Result>("[DB_SMARTEntities1].[fGenerateUsernamePassword](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetInboxByRekanan")]
        public virtual IQueryable<fGetInboxByRekanan_Result> fGetInboxByRekanan(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetInboxByRekanan_Result>("[DB_SMARTEntities1].[fGetInboxByRekanan](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetNotiByIdNotification")]
        public virtual IQueryable<fGetNotiByIdNotification_Result> fGetNotiByIdNotification(Nullable<int> idNotification)
        {
            var idNotificationParameter = idNotification.HasValue ?
                new ObjectParameter("IdNotification", idNotification) :
                new ObjectParameter("IdNotification", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetNotiByIdNotification_Result>("[DB_SMARTEntities1].[fGetNotiByIdNotification](@IdNotification)", idNotificationParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetNotificationBySubject")]
        public virtual IQueryable<fGetNotificationBySubject_Result> fGetNotificationBySubject(Nullable<System.Guid> subjetTo, Nullable<int> levelUrgensi)
        {
            var subjetToParameter = subjetTo.HasValue ?
                new ObjectParameter("SubjetTo", subjetTo) :
                new ObjectParameter("SubjetTo", typeof(System.Guid));
    
            var levelUrgensiParameter = levelUrgensi.HasValue ?
                new ObjectParameter("LevelUrgensi", levelUrgensi) :
                new ObjectParameter("LevelUrgensi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetNotificationBySubject_Result>("[DB_SMARTEntities1].[fGetNotificationBySubject](@SubjetTo, @LevelUrgensi)", subjetToParameter, levelUrgensiParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetPekerjaan3MByIdTypeOfRekanan")]
        public virtual IQueryable<fGetPekerjaan3MByIdTypeOfRekanan_Result> fGetPekerjaan3MByIdTypeOfRekanan(Nullable<int> idTypeOfRekanan)
        {
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetPekerjaan3MByIdTypeOfRekanan_Result>("[DB_SMARTEntities1].[fGetPekerjaan3MByIdTypeOfRekanan](@IdTypeOfRekanan)", idTypeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetPengumumanByTypeOfRekanan")]
        public virtual IQueryable<fGetPengumumanByTypeOfRekanan_Result> fGetPengumumanByTypeOfRekanan(Nullable<int> idTypeOfRekanan)
        {
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetPengumumanByTypeOfRekanan_Result>("[DB_SMARTEntities1].[fGetPengumumanByTypeOfRekanan](@IdTypeOfRekanan)", idTypeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetSupervisorByRek")]
        public virtual IQueryable<fGetSupervisorByRek_Result> fGetSupervisorByRek(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetSupervisorByRek_Result>("[DB_SMARTEntities1].[fGetSupervisorByRek](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetTDraftCaptionBySubjectFrom")]
        public virtual IQueryable<fGetTDraftCaptionBySubjectFrom_Result> fGetTDraftCaptionBySubjectFrom(string subjectFrom)
        {
            var subjectFromParameter = subjectFrom != null ?
                new ObjectParameter("SubjectFrom", subjectFrom) :
                new ObjectParameter("SubjectFrom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetTDraftCaptionBySubjectFrom_Result>("[DB_SMARTEntities1].[fGetTDraftCaptionBySubjectFrom](@SubjectFrom)", subjectFromParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetTDraftDetailBySubjectFrom")]
        public virtual IQueryable<fGetTDraftDetailBySubjectFrom_Result> fGetTDraftDetailBySubjectFrom(Nullable<System.Guid> subjectFrom)
        {
            var subjectFromParameter = subjectFrom.HasValue ?
                new ObjectParameter("SubjectFrom", subjectFrom) :
                new ObjectParameter("SubjectFrom", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetTDraftDetailBySubjectFrom_Result>("[DB_SMARTEntities1].[fGetTDraftDetailBySubjectFrom](@SubjectFrom)", subjectFromParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetTInboxCaptionBySubjectTo")]
        public virtual IQueryable<fGetTInboxCaptionBySubjectTo_Result> fGetTInboxCaptionBySubjectTo(Nullable<System.Guid> subjectTo)
        {
            var subjectToParameter = subjectTo.HasValue ?
                new ObjectParameter("SubjectTo", subjectTo) :
                new ObjectParameter("SubjectTo", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetTInboxCaptionBySubjectTo_Result>("[DB_SMARTEntities1].[fGetTInboxCaptionBySubjectTo](@SubjectTo)", subjectToParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetTInboxDetailBySubjectTo")]
        public virtual IQueryable<fGetTInboxDetailBySubjectTo_Result> fGetTInboxDetailBySubjectTo(Nullable<System.Guid> subjectTo)
        {
            var subjectToParameter = subjectTo.HasValue ?
                new ObjectParameter("SubjectTo", subjectTo) :
                new ObjectParameter("SubjectTo", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetTInboxDetailBySubjectTo_Result>("[DB_SMARTEntities1].[fGetTInboxDetailBySubjectTo](@SubjectTo)", subjectToParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetTSentDetailBySubjectFrom")]
        public virtual IQueryable<fGetTSentDetailBySubjectFrom_Result> fGetTSentDetailBySubjectFrom(Nullable<System.Guid> subjectFrom)
        {
            var subjectFromParameter = subjectFrom.HasValue ?
                new ObjectParameter("SubjectFrom", subjectFrom) :
                new ObjectParameter("SubjectFrom", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetTSentDetailBySubjectFrom_Result>("[DB_SMARTEntities1].[fGetTSentDetailBySubjectFrom](@SubjectFrom)", subjectFromParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fInfoLastModifiedByRek")]
        public virtual IQueryable<fInfoLastModifiedByRek_Result> fInfoLastModifiedByRek(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fInfoLastModifiedByRek_Result>("[DB_SMARTEntities1].[fInfoLastModifiedByRek](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fMasukMasaRegistrasi")]
        public virtual IQueryable<fMasukMasaRegistrasi_Result> fMasukMasaRegistrasi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fMasukMasaRegistrasi_Result>("[DB_SMARTEntities1].[fMasukMasaRegistrasi]()");
        }
    
        [DbFunction("DB_SMARTEntities1", "fPekerjaanAS_3MByTypeOfRekanan")]
        public virtual IQueryable<fPekerjaanAS_3MByTypeOfRekanan_Result> fPekerjaanAS_3MByTypeOfRekanan(Nullable<int> idTypeOfRekanan)
        {
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fPekerjaanAS_3MByTypeOfRekanan_Result>("[DB_SMARTEntities1].[fPekerjaanAS_3MByTypeOfRekanan](@IdTypeOfRekanan)", idTypeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fPekerjaanBLGByTypeOfRekanan")]
        public virtual IQueryable<fPekerjaanBLGByTypeOfRekanan_Result> fPekerjaanBLGByTypeOfRekanan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fPekerjaanBLGByTypeOfRekanan_Result>("[DB_SMARTEntities1].[fPekerjaanBLGByTypeOfRekanan]()");
        }
    
        [DbFunction("DB_SMARTEntities1", "fPekerjaanByTypeOfRekanan")]
        public virtual IQueryable<fPekerjaanByTypeOfRekanan_Result> fPekerjaanByTypeOfRekanan(Nullable<int> idTypeOfRekanan)
        {
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fPekerjaanByTypeOfRekanan_Result>("[DB_SMARTEntities1].[fPekerjaanByTypeOfRekanan](@IdTypeOfRekanan)", idTypeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fReadInfoByIdNotification")]
        public virtual IQueryable<fReadInfoByIdNotification_Result> fReadInfoByIdNotification(Nullable<int> idNotificationDetail, Nullable<bool> flgTraySent)
        {
            var idNotificationDetailParameter = idNotificationDetail.HasValue ?
                new ObjectParameter("IdNotificationDetail", idNotificationDetail) :
                new ObjectParameter("IdNotificationDetail", typeof(int));
    
            var flgTraySentParameter = flgTraySent.HasValue ?
                new ObjectParameter("flgTraySent", flgTraySent) :
                new ObjectParameter("flgTraySent", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fReadInfoByIdNotification_Result>("[DB_SMARTEntities1].[fReadInfoByIdNotification](@IdNotificationDetail, @flgTraySent)", idNotificationDetailParameter, flgTraySentParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fTotDocumentDetailByRek")]
        public virtual IQueryable<fTotDocumentDetailByRek_Result> fTotDocumentDetailByRek(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fTotDocumentDetailByRek_Result>("[DB_SMARTEntities1].[fTotDocumentDetailByRek](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fXLS_RekByIdSupervisor")]
        public virtual IQueryable<fXLS_RekByIdSupervisor_Result> fXLS_RekByIdSupervisor(Nullable<int> idSupervisor)
        {
            var idSupervisorParameter = idSupervisor.HasValue ?
                new ObjectParameter("IdSupervisor", idSupervisor) :
                new ObjectParameter("IdSupervisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fXLS_RekByIdSupervisor_Result>("[DB_SMARTEntities1].[fXLS_RekByIdSupervisor](@IdSupervisor)", idSupervisorParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "splitstring")]
        public virtual IQueryable<splitstring_Result> splitstring(string stringToSplit)
        {
            var stringToSplitParameter = stringToSplit != null ?
                new ObjectParameter("stringToSplit", stringToSplit) :
                new ObjectParameter("stringToSplit", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<splitstring_Result>("[DB_SMARTEntities1].[splitstring](@stringToSplit)", stringToSplitParameter);
        }
    
        public virtual int spPopulateRecipient(Nullable<int> idNotification, string arrRecipient, string createdUser, Nullable<bool> flagKirim, Nullable<System.DateTime> sentDate, Nullable<bool> flagSaluranEmail, Nullable<bool> flagSaluranWhatsapp)
        {
            var idNotificationParameter = idNotification.HasValue ?
                new ObjectParameter("IdNotification", idNotification) :
                new ObjectParameter("IdNotification", typeof(int));
    
            var arrRecipientParameter = arrRecipient != null ?
                new ObjectParameter("ArrRecipient", arrRecipient) :
                new ObjectParameter("ArrRecipient", typeof(string));
    
            var createdUserParameter = createdUser != null ?
                new ObjectParameter("CreatedUser", createdUser) :
                new ObjectParameter("CreatedUser", typeof(string));
    
            var flagKirimParameter = flagKirim.HasValue ?
                new ObjectParameter("FlagKirim", flagKirim) :
                new ObjectParameter("FlagKirim", typeof(bool));
    
            var sentDateParameter = sentDate.HasValue ?
                new ObjectParameter("SentDate", sentDate) :
                new ObjectParameter("SentDate", typeof(System.DateTime));
    
            var flagSaluranEmailParameter = flagSaluranEmail.HasValue ?
                new ObjectParameter("FlagSaluranEmail", flagSaluranEmail) :
                new ObjectParameter("FlagSaluranEmail", typeof(bool));
    
            var flagSaluranWhatsappParameter = flagSaluranWhatsapp.HasValue ?
                new ObjectParameter("FlagSaluranWhatsapp", flagSaluranWhatsapp) :
                new ObjectParameter("FlagSaluranWhatsapp", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spPopulateRecipient", idNotificationParameter, arrRecipientParameter, createdUserParameter, flagKirimParameter, sentDateParameter, flagSaluranEmailParameter, flagSaluranWhatsappParameter);
        }
    
        public virtual int spTranDataBranch(Nullable<System.Guid> guidHeader)
        {
            var guidHeaderParameter = guidHeader.HasValue ?
                new ObjectParameter("GuidHeader", guidHeader) :
                new ObjectParameter("GuidHeader", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTranDataBranch", guidHeaderParameter);
        }
    
        public virtual int spTranDataDetailPekerjaan(Nullable<System.Guid> guidHeader)
        {
            var guidHeaderParameter = guidHeader.HasValue ?
                new ObjectParameter("GuidHeader", guidHeader) :
                new ObjectParameter("GuidHeader", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTranDataDetailPekerjaan", guidHeaderParameter);
        }
    
        public virtual int spTranDataDetailPekerjaanAS_1M(Nullable<System.Guid> guidHeader)
        {
            var guidHeaderParameter = guidHeader.HasValue ?
                new ObjectParameter("GuidHeader", guidHeader) :
                new ObjectParameter("GuidHeader", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTranDataDetailPekerjaanAS_1M", guidHeaderParameter);
        }
    
        public virtual int spTranDataTenagaAhli(Nullable<System.Guid> guidHeader)
        {
            var guidHeaderParameter = guidHeader.HasValue ?
                new ObjectParameter("GuidHeader", guidHeader) :
                new ObjectParameter("GuidHeader", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTranDataTenagaAhli", guidHeaderParameter);
        }
    
        public virtual int spTranDataTenagaAhliTidakTetap(Nullable<System.Guid> guidHeader)
        {
            var guidHeaderParameter = guidHeader.HasValue ?
                new ObjectParameter("GuidHeader", guidHeader) :
                new ObjectParameter("GuidHeader", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTranDataTenagaAhliTidakTetap", guidHeaderParameter);
        }
    
        public virtual int spTranDataTenagaPendukung(Nullable<System.Guid> guidHeader)
        {
            var guidHeaderParameter = guidHeader.HasValue ?
                new ObjectParameter("GuidHeader", guidHeader) :
                new ObjectParameter("GuidHeader", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTranDataTenagaPendukung", guidHeaderParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashFeeByRekananFinal")]
        public virtual IQueryable<fDashFeeByRekananFinal_Result> fDashFeeByRekananFinal(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashFeeByRekananFinal_Result>("[DB_SMARTEntities1].[fDashFeeByRekananFinal](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDashPekerjaanByRekananFinal")]
        public virtual IQueryable<fDashPekerjaanByRekananFinal_Result> fDashPekerjaanByRekananFinal(Nullable<int> tahun, Nullable<int> topN, Nullable<int> typeOfRekanan)
        {
            var tahunParameter = tahun.HasValue ?
                new ObjectParameter("Tahun", tahun) :
                new ObjectParameter("Tahun", typeof(int));
    
            var topNParameter = topN.HasValue ?
                new ObjectParameter("TopN", topN) :
                new ObjectParameter("TopN", typeof(int));
    
            var typeOfRekananParameter = typeOfRekanan.HasValue ?
                new ObjectParameter("TypeOfRekanan", typeOfRekanan) :
                new ObjectParameter("TypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDashPekerjaanByRekananFinal_Result>("[DB_SMARTEntities1].[fDashPekerjaanByRekananFinal](@Tahun, @TopN, @TypeOfRekanan)", tahunParameter, topNParameter, typeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fManagementRekanan")]
        public virtual IQueryable<fManagementRekanan_Result> fManagementRekanan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fManagementRekanan_Result>("[DB_SMARTEntities1].[fManagementRekanan]()");
        }
    
        [DbFunction("DB_SMARTEntities1", "fPekerjaanAS_1MByTypeOfRekanan")]
        public virtual IQueryable<fPekerjaanAS_1MByTypeOfRekanan_Result> fPekerjaanAS_1MByTypeOfRekanan(Nullable<int> idTypeOfRekanan)
        {
            var idTypeOfRekananParameter = idTypeOfRekanan.HasValue ?
                new ObjectParameter("IdTypeOfRekanan", idTypeOfRekanan) :
                new ObjectParameter("IdTypeOfRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fPekerjaanAS_1MByTypeOfRekanan_Result>("[DB_SMARTEntities1].[fPekerjaanAS_1MByTypeOfRekanan](@IdTypeOfRekanan)", idTypeOfRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fInfo2LastModifiedByRek")]
        public virtual IQueryable<fInfo2LastModifiedByRek_Result> fInfo2LastModifiedByRek(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fInfo2LastModifiedByRek_Result>("[DB_SMARTEntities1].[fInfo2LastModifiedByRek](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetRekananByIdSupervisor")]
        public virtual IQueryable<fGetRekananByIdSupervisor_Result> fGetRekananByIdSupervisor(Nullable<int> idSupervisor)
        {
            var idSupervisorParameter = idSupervisor.HasValue ?
                new ObjectParameter("IdSupervisor", idSupervisor) :
                new ObjectParameter("IdSupervisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetRekananByIdSupervisor_Result>("[DB_SMARTEntities1].[fGetRekananByIdSupervisor](@IdSupervisor)", idSupervisorParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetLapAS1MByRekanan")]
        public virtual IQueryable<fGetLapAS1MByRekanan_Result> fGetLapAS1MByRekanan(Nullable<System.Guid> idRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetLapAS1MByRekanan_Result>("[DB_SMARTEntities1].[fGetLapAS1MByRekanan](@IdRekanan)", idRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetTSentCaptionBySubjectFrom")]
        public virtual IQueryable<fGetTSentCaptionBySubjectFrom_Result> fGetTSentCaptionBySubjectFrom(Nullable<System.Guid> subjectFrom, Nullable<int> idTipeSaluran)
        {
            var subjectFromParameter = subjectFrom.HasValue ?
                new ObjectParameter("SubjectFrom", subjectFrom) :
                new ObjectParameter("SubjectFrom", typeof(System.Guid));
    
            var idTipeSaluranParameter = idTipeSaluran.HasValue ?
                new ObjectParameter("IdTipeSaluran", idTipeSaluran) :
                new ObjectParameter("IdTipeSaluran", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetTSentCaptionBySubjectFrom_Result>("[DB_SMARTEntities1].[fGetTSentCaptionBySubjectFrom](@SubjectFrom, @IdTipeSaluran)", subjectFromParameter, idTipeSaluranParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fGetSentByIdNotification")]
        public virtual IQueryable<fGetSentByIdNotification_Result> fGetSentByIdNotification(Nullable<int> idNotification, Nullable<int> idTipeSaluran)
        {
            var idNotificationParameter = idNotification.HasValue ?
                new ObjectParameter("IdNotification", idNotification) :
                new ObjectParameter("IdNotification", typeof(int));
    
            var idTipeSaluranParameter = idTipeSaluran.HasValue ?
                new ObjectParameter("IdTipeSaluran", idTipeSaluran) :
                new ObjectParameter("IdTipeSaluran", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fGetSentByIdNotification_Result>("[DB_SMARTEntities1].[fGetSentByIdNotification](@IdNotification, @IdTipeSaluran)", idNotificationParameter, idTipeSaluranParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fKategoriResiko")]
        public virtual IQueryable<fKategoriResiko_Result> fKategoriResiko(Nullable<decimal> penambah)
        {
            var penambahParameter = penambah.HasValue ?
                new ObjectParameter("Penambah", penambah) :
                new ObjectParameter("Penambah", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fKategoriResiko_Result>("[DB_SMARTEntities1].[fKategoriResiko](@Penambah)", penambahParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fKonsoByPeriode")]
        public virtual IQueryable<fKonsoByPeriode_Result> fKonsoByPeriode(Nullable<System.Guid> idRekanan, Nullable<int> periode)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("Periode", periode) :
                new ObjectParameter("Periode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fKonsoByPeriode_Result>("[DB_SMARTEntities1].[fKonsoByPeriode](@IdRekanan, @Periode)", idRekananParameter, periodeParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fKonsoResumeByPeriode")]
        public virtual IQueryable<fKonsoResumeByPeriode_Result> fKonsoResumeByPeriode(Nullable<System.Guid> idRekanan, Nullable<int> periodeAwal, Nullable<int> periodeAkhir, Nullable<int> tipeUraian)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var periodeAwalParameter = periodeAwal.HasValue ?
                new ObjectParameter("PeriodeAwal", periodeAwal) :
                new ObjectParameter("PeriodeAwal", typeof(int));
    
            var periodeAkhirParameter = periodeAkhir.HasValue ?
                new ObjectParameter("PeriodeAkhir", periodeAkhir) :
                new ObjectParameter("PeriodeAkhir", typeof(int));
    
            var tipeUraianParameter = tipeUraian.HasValue ?
                new ObjectParameter("TipeUraian", tipeUraian) :
                new ObjectParameter("TipeUraian", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fKonsoResumeByPeriode_Result>("[DB_SMARTEntities1].[fKonsoResumeByPeriode](@IdRekanan, @PeriodeAwal, @PeriodeAkhir, @TipeUraian)", idRekananParameter, periodeAwalParameter, periodeAkhirParameter, tipeUraianParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fDataOrganisasiByRek_Type")]
        public virtual IQueryable<fDataOrganisasiByRek_Type_Result> fDataOrganisasiByRek_Type(Nullable<System.Guid> idRekanan, Nullable<int> tipeRekanan)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var tipeRekananParameter = tipeRekanan.HasValue ?
                new ObjectParameter("TipeRekanan", tipeRekanan) :
                new ObjectParameter("TipeRekanan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fDataOrganisasiByRek_Type_Result>("[DB_SMARTEntities1].[fDataOrganisasiByRek_Type](@IdRekanan, @TipeRekanan)", idRekananParameter, tipeRekananParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fScoringResumeByRek")]
        public virtual IQueryable<fScoringResumeByRek_Result> fScoringResumeByRek(Nullable<System.Guid> idRekanan, Nullable<int> periode)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("Periode", periode) :
                new ObjectParameter("Periode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fScoringResumeByRek_Result>("[DB_SMARTEntities1].[fScoringResumeByRek](@IdRekanan, @Periode)", idRekananParameter, periodeParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fScoringByPeriode")]
        public virtual IQueryable<fScoringByPeriode_Result> fScoringByPeriode(Nullable<System.Guid> idRekanan, Nullable<int> periode)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("Periode", periode) :
                new ObjectParameter("Periode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fScoringByPeriode_Result>("[DB_SMARTEntities1].[fScoringByPeriode](@IdRekanan, @Periode)", idRekananParameter, periodeParameter);
        }
    
        [DbFunction("DB_SMARTEntities1", "fResumeRoaByPeriode")]
        public virtual IQueryable<fResumeRoaByPeriode_Result> fResumeRoaByPeriode(Nullable<System.Guid> idRekanan, Nullable<int> periode)
        {
            var idRekananParameter = idRekanan.HasValue ?
                new ObjectParameter("IdRekanan", idRekanan) :
                new ObjectParameter("IdRekanan", typeof(System.Guid));
    
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("Periode", periode) :
                new ObjectParameter("Periode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fResumeRoaByPeriode_Result>("[DB_SMARTEntities1].[fResumeRoaByPeriode](@IdRekanan, @Periode)", idRekananParameter, periodeParameter);
        }
    }
}
