//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstScoreValue
    {
        public int IdScoreValue { get; set; }
        public int IdTypeOfRekanan { get; set; }
        public string ScoreType { get; set; }
        public string ScoreDescription { get; set; }
        public int ScoreValue { get; set; }
    }
}
