//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptAsuransi
    {
        public int IdRptAsuransi { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int r_IdJenisAsuransi { get; set; }
        public int r_CadanganTeknis { get; set; }
        public int r_TotalInvestasi { get; set; }
        public int r_HasilInvestasi { get; set; }
        public int r_LabaBeforeTax { get; set; }
        public int r_PremiNetto { get; set; }
        public int r_PremiBruttoPrevY { get; set; }
        public int r_PremiBruttoCurY { get; set; }
        public int r_TotalAktiva { get; set; }
        public int r_AktivaLancar { get; set; }
        public int r_KewajibanLancar { get; set; }
        public int r_BebanKomisiBersih { get; set; }
        public int r_BebanUsaha { get; set; }
        public int r_TanahBangunan { get; set; }
        public int r_JumlahKewajibanPolis { get; set; }
        public int r_JumlahKlaimManfaat { get; set; }
        public int r_LabaRugi { get; set; }
        public int r_RBC_Q4 { get; set; }
        public int r_TotalEkuitasPrevY { get; set; }
        public int r_TotalEkuitasCurY { get; set; }
        public int r_JaringanKantor { get; set; }
        public int r_KapasitasTreaty { get; set; }
        public int r_RasioDanaInvestasi { get; set; }
        public int a_IdReputasiUmum { get; set; }
        public int a_IdKarakterBonafiditasUmum { get; set; }
        public int a_IdKinerjaPembayaranKlaim { get; set; }
        public int a_IdPelayananUmumJiwa { get; set; }
        public int a_IdPortfolioBankLain { get; set; }
        public int a_IdSpesialisasiBisnisUmum { get; set; }
        public int a_IdDukunganLembagaP { get; set; }
        public int a_IdReputasiJiwa { get; set; }
        public int a_IdKarakterBonafiditasJiwa { get; set; }
        public int a_IdRatingJiwa { get; set; }
        public int a_IdJenisScoreKualitatif { get; set; }
    }
}
