//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptKAP
    {
        public int IdRptKAP { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int r_IdJenisReview { get; set; }
        public string r_Alamat { get; set; }
        public string r_Telepon { get; set; }
        public string r_Fax { get; set; }
        public string r_Email { get; set; }
        public string r_HP { get; set; }
        public int r_Pengalaman { get; set; }
        public int r_Partner { get; set; }
        public int r_TenagaAkuntanPublik { get; set; }
        public int r_Auditor { get; set; }
        public int r_PartnerTerdaftar { get; set; }
        public int r_Afiliasi { get; set; }
        public int r_Cabang { get; set; }
        public int r_KlienAset300M { get; set; }
        public int a_ValReputasi { get; set; }
        public int a_ValKinerja { get; set; }
        public int a_ValPelayanan { get; set; }
        public int a_ValAdministratif { get; set; }
        public int a_IdTambahanKlasifikasi { get; set; }
    }
}
