//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptKJPP
    {
        public int IdRptKJPP { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int r_IdJenisReview { get; set; }
        public string r_Alamat { get; set; }
        public string r_Telepon { get; set; }
        public string r_Fax { get; set; }
        public string r_Email { get; set; }
        public string r_HP { get; set; }
        public int r_Pengalaman { get; set; }
        public int r_TenagaSurvey { get; set; }
        public int r_TenagaAhliBeregister { get; set; }
        public int r_TenagaAhliBerizin { get; set; }
        public int r_CabangLuar { get; set; }
        public int r_PenilaianAset100M { get; set; }
        public int a_ValReputasi { get; set; }
        public int a_ValKinerja { get; set; }
        public int a_ValPelayanan { get; set; }
        public int a_ValAdministratif { get; set; }
        public int a_IdTambahanKlasifikasi { get; set; }
    }
}
