//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxBranchOffice
    {
        public int IdCabang { get; set; }
        public System.Guid GuidHeader { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int IdOrganisasi { get; set; }
        public int BranchType { get; set; }
        public int JumlahPegawai { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public Nullable<int> IdWilayah { get; set; }
        public Nullable<int> IdKecamatan { get; set; }
        public string ZipCode { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
