//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxDocMandatoryDetail
    {
        public int IdDocMandatoryDetail { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int IdTypeOfDocument { get; set; }
        public string nomorDokumen { get; set; }
        public string badanPembuatDokumen { get; set; }
        public Nullable<System.DateTime> tanggalAwal { get; set; }
        public Nullable<System.DateTime> tanggalAkhir { get; set; }
        public string catatan { get; set; }
        public Nullable<System.Guid> ImageBaseName { get; set; }
        public string FileExt { get; set; }
        public string FileExt2 { get; set; }
        public string ProcInfo { get; set; }
        public System.DateTime LMDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
