//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxDocMandatoryFile
    {
        public int IdDocMandatoryFile { get; set; }
        public int IdDocMandatoryDetail { get; set; }
        public string namaFile { get; set; }
    }
}
