//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxDetailPekerjaanAS_Tahunan
    {
        public int Id { get; set; }
        public System.Guid IdRekanan { get; set; }
        public Nullable<byte> IdTypeOfAsuransi { get; set; }
        public Nullable<long> LabaRugiKomprehensif { get; set; }
        public Nullable<long> CadanganTeknis { get; set; }
        public Nullable<long> TotalInvestasi { get; set; }
        public Nullable<long> HasilInvestasi { get; set; }
        public Nullable<long> LabaBeforeTax { get; set; }
        public Nullable<long> PremiNettoPeriodeReview { get; set; }
        public Nullable<long> PremiBrutoSebelumPeriodeReview { get; set; }
        public Nullable<long> PremiBrutoPeriodeReview { get; set; }
        public Nullable<long> TotalAktiva { get; set; }
        public Nullable<long> AktivaLancar { get; set; }
        public Nullable<long> KewajibanLancar { get; set; }
        public Nullable<long> BebanKomisiBersih { get; set; }
        public Nullable<long> BebanUsaha { get; set; }
        public Nullable<long> TanahBangunan { get; set; }
        public Nullable<long> JumlahKewajibanKepadaPemegangPolis { get; set; }
        public Nullable<long> JumlahKlaimDanManfaat { get; set; }
        public Nullable<long> RBCSebelumPeriodeReview { get; set; }
        public Nullable<long> RBCPeriodeReview { get; set; }
        public Nullable<long> TotalEkuitasSebelumPeriodeReview { get; set; }
        public Nullable<long> TotalEkuitasPeriodeReview { get; set; }
        public Nullable<int> JaringanKantor { get; set; }
        public Nullable<long> KapasitasTreaty { get; set; }
        public Nullable<long> RasioDanaInvestasiPadaGroup { get; set; }
        public Nullable<byte> ReputasiUmum_Id { get; set; }
        public Nullable<byte> KarakterDanBonafiditasOwnerUmum_Id { get; set; }
        public Nullable<byte> KinerjaPembayaranKlaimUmumJiwa_Id { get; set; }
        public Nullable<byte> PelayananUmumJiwa_Id { get; set; }
        public Nullable<byte> PortofolioDiBankLainUmumJiwa_Id { get; set; }
        public Nullable<byte> SpesialisasiBisnisUmumJiwa_Id { get; set; }
        public Nullable<byte> DukunganLembagaPenunjangUmumJiwa_Id { get; set; }
        public Nullable<byte> ReputasiJiwa_Id { get; set; }
        public Nullable<byte> KarakterDanBonafiditasOwnerJiwa_Id { get; set; }
        public Nullable<byte> RatingJiwa_Id { get; set; }
        public Nullable<byte> JenisScoreKualitatif_Id { get; set; }
    }
}
