//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxFileScanned
    {
        public int IdFileScanned { get; set; }
        public System.Guid ImageBaseName { get; set; }
        public string NamaInternal { get; set; }
        public string EkstensiFile { get; set; }
        public string Nama { get; set; }
        public string Catatan { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
