//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxNotarisItem
    {
        public int IdNotarisItem { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string Name { get; set; }
        public string RoleTitle { get; set; }
        public string Alamat { get; set; }
        public string NomorKTP { get; set; }
        public string NomorNPWP { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Handphone1 { get; set; }
        public string Handphone2 { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public Nullable<System.Guid> ImageBaseName { get; set; }
        public string FileExtKTP { get; set; }
        public string FileExtNPWP { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> TanggalMulaiBlacklist { get; set; }
        public Nullable<System.DateTime> TanggalAkhirBlacklist { get; set; }
        public bool StatusBlackList { get; set; }
        public string Catatan { get; set; }
    }
}
