//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxPertanyaan
    {
        public int IdTPertanyaan { get; set; }
        public int IdPertanyaan { get; set; }
        public int IdTypeOfGroup { get; set; }
        public int SeqPertanyaan { get; set; }
        public int Bobot { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    }
}
