//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxRekananDocumentTrack
    {
        public int IdDocumentTrack { get; set; }
        public int IdDocument { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int IdTypeOfDocument { get; set; }
        public int IdTypeOfStatusDoc { get; set; }
        public string VerificationNote { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
