//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxSanksiEksternal_ARC
    {
        public int IdArc { get; set; }
        public int IdAction { get; set; }
        public int IdSanksiEksternal { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string SanksiType { get; set; }
        public string Pelanggaran { get; set; }
        public string LetterNumber { get; set; }
        public Nullable<System.DateTime> LetterDate { get; set; }
        public Nullable<int> Period { get; set; }
        public string SanksiStatus { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
