//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxTenagaAhliTidakTetapImp
    {
        public int IdTenaga { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string NamaLengkap { get; set; }
        public string TanggalMulai { get; set; }
        public string JenisKantor { get; set; }
        public string NamaKantor { get; set; }
        public string NomorKTP { get; set; }
        public string NomorNPWP { get; set; }
        public string NomorIAPI { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
