//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPertanyaanNilaiAkhir
    {
        public System.Guid IdRekanan { get; set; }
        public string Deskripsi { get; set; }
        public Nullable<decimal> TotPPG { get; set; }
        public Nullable<decimal> TotFOG { get; set; }
        public Nullable<decimal> AvgScore { get; set; }
        public int Urutan { get; set; }
    }
}
