//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPertanyaanNilai
    {
        public int IdTNPertanyaan { get; set; }
        public int IdTypeOfGroup { get; set; }
        public int IdPenilai { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int TahunBulan { get; set; }
        public int SeqPertanyaan { get; set; }
        public string Deskripsi { get; set; }
        public int Bobot { get; set; }
        public int Nilai { get; set; }
        public Nullable<decimal> Score { get; set; }
    }
}
