//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRekManagemenBL
    {
        public int IdManagemen { get; set; }
        public int BlackListed { get; set; }
        public string Kode { get; set; }
        public string RegistrationNumber { get; set; }
        public string Rekanan { get; set; }
        public string Name { get; set; }
        public string Alamat { get; set; }
        public string NomorKTP { get; set; }
        public string NomorNPWP { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Catatan { get; set; }
        public Nullable<System.DateTime> TanggalMulaiBlackList { get; set; }
        public Nullable<System.DateTime> TanggalAkhirBlacklist { get; set; }
    }
}
