//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class fInfoLastModifiedByRek_Result
    {
        public int mySeq { get; set; }
        public string Judul_Informasi { get; set; }
        public System.DateTime Last_Modified { get; set; }
    }
}
