//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;

    public partial class fInfo2LastModifiedByRek_Result
    {
        public int Grupinfo1 { get; set; }
        public string Judul_Informasi { get; set; }
        public string LastModified { get; set; }
    }
}
