//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class fKonsoResumeByPeriode_Result
    {
        public int idMstKonsolidasi { get; set; }
        public string Ikhtisar { get; set; }
        public Nullable<decimal> myValueAkhir { get; set; }
        public Nullable<decimal> myValueAwal { get; set; }
        public Nullable<int> TumbuhSign { get; set; }
        public Nullable<decimal> TumbuhPercent { get; set; }
        public int SeqResume { get; set; }
    }
}
