//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;    
    public partial class mstDataMaster
    {
        public IEnumerable<mstTypeOfRekanan> TypeOfRekananColls { get; set; }
        public IEnumerable<mstTypeOfRegion> TypeOfRegionColls { get; set; }
        public IEnumerable<mstSegmentasi> TypeOfSegmentasi3Colls { get; set; }
        public IEnumerable<mstSegmentasi> TypeOfSegmentasi5Colls { get; set; }
        public IEnumerable<mstSubRegion> SubRegionColls { get; set; }
        public IEnumerable<mstReference> TypeTotalAsetColls { get; set; }
        public IEnumerable<mstReference> TriwulanColls { get; set; }
        public IEnumerable<mstReference> TingkatResikoColls { get; set; }
        public IEnumerable<mstReference> LbgPemeringkatColls { get; set; }
    }
}
