//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PertanyaanNilaiMulti
    {
        public List<vwPertanyaanNilai> PertanyaanColls { get; set; }
        public List<SimpleRef> PilihanScore { get; set; }
    }
}
