//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class trxDetailPekerjaanAS_1MMulti
    {
        public IEnumerable<trxDetailPekerjaanAS_1M> DetailPekerjaanColls { get; set; }
        public IEnumerable<fPekerjaanAS_1MByTypeOfRekanan_Result> XLSDetailPekerjaanColls { get; set; }
        public IEnumerable<fGetLapAS1MByRekanan_Result> XLSAS1MDetailPekerjaanColls { get; set; }
        public IEnumerable<mstSubRegion> SubRegionColls { get; set; }
        public IEnumerable<mstSegmentasi> TypeOfSegmentasi3Colls { get; set; }
        public IEnumerable<mstSegmentasi> TypeOfSegmentasi5Colls { get; set; }
    }
}
