//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class trxRekananDocumentMulti
    {
        public IEnumerable<trxDocumentMandatory> TrxRekananDocumentMulti { get; set; }
        public IEnumerable<mstTypeOfDocument> TypeOfDocumentColls { get; set; }
        public IEnumerable<trxRekananDocument> TrxRekananDocumentMaster { get; set; }
        public IEnumerable<fTotDocumentDetailByRek_Result> TotDocDetailByRekanan { get; set; }
    }
}
