//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class dashFeeByRekanan
    {
        public Nullable<int> IdSupervisor { get; set; }
        public Nullable<int> KelasRangking { get; set; }
        public string NamaRekanan { get; set; }
        public Nullable<decimal> TotalFee { get; set; }
        public Nullable<decimal> TotalFeeAll { get; set; }
        public Nullable<decimal> Persen { get; set; }
    }
}
