//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptBalaiLelang
    {
        public int IdRptBalaiLelang { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int r_IdJenisReview { get; set; }
        public string r_Alamat { get; set; }
        public string r_Telepon { get; set; }
        public string r_Fax { get; set; }
        public string r_Email { get; set; }
        public string r_HP { get; set; }
        public int r_ValPerizinanLegalitas { get; set; }
        public int r_ValSaranaPendukung { get; set; }
        public int r_PengalamanPengurus { get; set; }
        public int r_ValKinerjaPerusahaan { get; set; }
        public int r_JumlahKantorCabang { get; set; }
        public int r_ValPengalamanPraLelang { get; set; }
        public int r_JumlahTenagaKerja { get; set; }
        public int r_JumlahModalSendiri { get; set; }
        public int r_ProfitMargin { get; set; }
    }
}
