//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptNotari
    {
        public int IdRptNotaris { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string r_Notaris { get; set; }
        public int r_IdJenisReview { get; set; }
        public string r_Alamat { get; set; }
        public string r_Telepon { get; set; }
        public string r_Fax { get; set; }
        public string r_Email { get; set; }
        public string r_HP { get; set; }
        public int r_MJabatanNotaris { get; set; }
        public int r_MJabatanPPAT { get; set; }
        public int r_TenagaKerja { get; set; }
        public int r_Asisten { get; set; }
        public int r_RataLimitKredit { get; set; }
        public int a_ValReputasi { get; set; }
        public int a_ValKinerja { get; set; }
        public int a_ValPelayanan { get; set; }
        public int a_ValAdministratif { get; set; }
        public Nullable<int> a_IdTambahanKlasifikasi { get; set; }
        public Nullable<System.DateTime> a_PensiunNotaris { get; set; }
        public Nullable<System.DateTime> a_PerpanjanganPensiunNotaris { get; set; }
        public Nullable<System.DateTime> a_PerpanjanganPensiunPPAT { get; set; }
    }
}
