//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emlNotification
    {
        public int IdEmailNotification { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int TemplateId { get; set; }
        public string ParameterKeys { get; set; }
        public string ParameterValues { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string AddressEmailIdTo { get; set; }
        public string AddressEmailIdCc { get; set; }
        public string AddressEmailTo { get; set; }
        public string AddressEmailCc { get; set; }
        public int StatusDelivery { get; set; }
        public System.DateTime MailCreationDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public bool FlagActivate { get; set; }
        public int SatuanPeriode { get; set; }
        public int CacahPeriode { get; set; }
        public System.DateTime TanggalJatuhTempo { get; set; }
        public System.DateTime TanggalNotifikasi { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
