//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class mstKategoriResiko
    {
        public int IdMstKategoriResiko { get; set; }
        public int IdTypeOfRekanan { get; set; }
        public bool IsKonsolidasi { get; set; }
        public string RangeNilaiC1 { get; set; }
        public decimal NilaiBawahC1 { get; set; }
        public decimal NilaiAtasC1 { get; set; }
        public decimal ScoreC1 { get; set; }
        public string RangeNilaiC2 { get; set; }
        public decimal NilaiBawahC2 { get; set; }
        public decimal NilaiAtasC2 { get; set; }
        public decimal ScoreC2 { get; set; }
        public string RangeNilaiC3 { get; set; }
        public decimal NilaiBawahC3 { get; set; }
        public decimal NilaiAtasC3 { get; set; }
        public decimal ScoreC3 { get; set; }
        public string RangeNilaiC4 { get; set; }
        public decimal NilaiBawahC4 { get; set; }
        public decimal NilaiAtasC4 { get; set; }
        public decimal ScoreC4 { get; set; }
        public int SeqPerKategori { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    }
}
