//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class mstProdukAsuransi
    {
        public int IdMstProdukAsuransi { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string NamaProduk { get; set; }
        public string NoIzinProduk { get; set; }
        public Nullable<System.DateTime> TanggalIzin { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    }
}
