//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class mstSubRegion
    {
        public int IdSubRegion { get; set; }
        public System.Guid IdRegionAdmin { get; set; }
        public string SubDescription { get; set; }
        public string LongDescription { get; set; }
        public bool IsActive { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
