//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class trxDocMandatoryVerification
    {
        public int IdTrxDocMandatoryVerification { get; set; }
        public System.Guid IdRekanan { get; set; }
        public int IdTypeOfDocument { get; set; }
        public bool IsVerified { get; set; }
        public string Catatan { get; set; }
        public Nullable<System.DateTime> LMDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
