//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class trxManagementBlackListHistory
    {
        public int IdManagemenBLHistory { get; set; }
        public Nullable<int> IdManagemen { get; set; }
        public string Name { get; set; }
        public string NomorKTP { get; set; }
        public string NomorNPWP { get; set; }
        public string NomorProfesi { get; set; }
        public Nullable<System.Guid> ImageBaseName { get; set; }
        public string FileExtKTP { get; set; }
        public string FileExtNPWP { get; set; }
        public string FileExtProfesi { get; set; }
        public System.DateTime TanggalMulaiBlackList { get; set; }
        public Nullable<System.DateTime> TanggalAkhirBlacklist { get; set; }
        public bool StatusBlackList { get; set; }
        public string Catatan { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
