//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxNotificationOld
    {
        public int IdNotification { get; set; }
        public System.Guid IdRekanan { get; set; }
        public bool IsTrayNotification { get; set; }
        public bool IsEmailNotification { get; set; }
        public string NotificationCaption { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime NotifyDate { get; set; }
        public int IdTemplate { get; set; }
        public bool IsNotifiedByTray { get; set; }
        public bool IsNotifiedByEmail { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
