//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class trxNotaris : HeaderViewModel
    {
        [Display(Name = "ID Notaris")]
        public int IdNotaris { get; set; }
        [Display(Name = "ID Rekanan")]
        public System.Guid IdRekanan { get; set; }
        [Display(Name = "SK Notaris")]
        public string SKNotaris { get; set; }
        [Display(Name = "Sumpah Notaris")]
        public string SumpahNotarisNumber { get; set; }
        [Display(Name = "Tanggal Sumpah")]
        public System.DateTime SumpahNotarisDate { get; set; }
        [Display(Name = "Kota")]
        public string City { get; set; }
        [Display(Name = "Anggota Koperasi")]
        public Nullable<bool> IsKoperasiMember { get; set; }
        [Display(Name = "SK Koperasi")]
        public string SKKoperasiNumber { get; set; }
        [Display(Name = "Tgl SK Koperasi")]
        public Nullable<System.DateTime> SKKoperasiDate { get; set; }
        public Nullable<bool> IsBapepamReg { get; set; }
        [Display(Name = "No. Bapepam")]
        public string BapepamSKNumber { get; set; }
        [Display(Name = "Tanggal Bapepam")]
        public Nullable<System.DateTime> BapepamSKDate { get; set; }
        [Display(Name = "Limit Atas")]
        public Nullable<int> UpLimit { get; set; }
        [Display(Name = "No. SKPPAT")]
        public string PPATSKNumber { get; set; }
        [Display(Name = "Tgl. SKPPAT")]
        public Nullable<System.DateTime> PPATSKDate { get; set; }
        [Display(Name = "No. Sumpah PPAT")]
        public string PPATSumpahNumber { get; set; }
        [Display(Name = "Tgl. Sumpah PPAT")]
        public Nullable<System.DateTime> PPATSumpahDate { get; set; }
        [Display(Name = "Wilayah PPAT")]
        public string WilayahKerjaPPAT { get; set; }
        [Display(Name = "Anggota IPPAT")]
        public Nullable<bool> IsIPPATMember { get; set; }
        [Display(Name = "SK IPPAT")]
        public string SKIPPATNumber { get; set; }
        [Display(Name = "Tgl. SKIPPAT")]
        public Nullable<System.DateTime> SKPPATDate { get; set; }
        [Display(Name = "Anggota INI")]
        public Nullable<bool> IsINIMember { get; set; }
        [Display(Name = "No. INI")]
        public string INISKNumber { get; set; }
        [Display(Name = "Tgl. SK INI")]
        public Nullable<System.DateTime> INISKDate { get; set; }
        [Display(Name = "Catatan")]
        public string Remark { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
