//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxNotificationDetail
    {
        public int IdNotificationDetail { get; set; }
        public int IdNotification { get; set; }
        public int IdTipeSaluran { get; set; }
        public System.Guid SubjectTo { get; set; }
        public string SubjectToAdd { get; set; }
        public System.Guid SubjectFrom { get; set; }
        public string SubjectFromAdd { get; set; }
        public bool flgTraySent { get; set; }
        public bool flgTrayRead { get; set; }
        public Nullable<System.DateTime> TSentDate { get; set; }
        public Nullable<System.DateTime> TReadDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
