//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class trxNotificationContent
    {
        public int IdNotificationContent { get; set; }
        public int IdNotification { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.Guid> Attachment { get; set; }
        public string FileExt1 { get; set; }
        public string FileExt2 { get; set; }
        public string FileExt3 { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }

}
