//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxNotificationHeader
    {
        public int IdNotification { get; set; }
        public int IdTipeNotification { get; set; }
        public int IdLevelUrgensi { get; set; }
        public string CaptionInfo { get; set; }
        public Nullable<int> IdDataProfilePart { get; set; }
        public Nullable<bool> flgValidity { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
