//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxNotaris_ARC
    {
        public int IdArc { get; set; }
        public int IdAction { get; set; }
        public int IdNotaris { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string SKNotaris { get; set; }
        public string SumpahNotarisNumber { get; set; }
        public System.DateTime SumpahNotarisDate { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsKoperasiMember { get; set; }
        public string SKKoperasiNumber { get; set; }
        public Nullable<System.DateTime> SKKoperasiDate { get; set; }
        public Nullable<bool> IsBapepamReg { get; set; }
        public string BapepamSKNumber { get; set; }
        public Nullable<System.DateTime> BapepamSKDate { get; set; }
        public Nullable<int> UpLimit { get; set; }
        public string PPATSKNumber { get; set; }
        public Nullable<System.DateTime> PPATSKDate { get; set; }
        public string PPATSumpahNumber { get; set; }
        public Nullable<System.DateTime> PPATSumpahDate { get; set; }
        public string WilayahKerjaPPAT { get; set; }
        public Nullable<bool> IsIPPATMember { get; set; }
        public string SKIPPATNumber { get; set; }
        public Nullable<System.DateTime> SKPPATDate { get; set; }
        public Nullable<bool> IsINIMember { get; set; }
        public string INISKNumber { get; set; }
        public Nullable<System.DateTime> INISKDate { get; set; }
        public string Remark { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
