//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxOwnership_ARC
    {
        public int IdArc { get; set; }
        public int IdAction { get; set; }
        public int IdOwnership { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string KTP { get; set; }
        public Nullable<System.DateTime> KTPEndDate { get; set; }
        public string Sertifikasi { get; set; }
        public Nullable<decimal> PercentSaham { get; set; }
        public Nullable<decimal> NominalSaham { get; set; }
        public Nullable<bool> IsKeyPerson { get; set; }
        public string NPWP { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
