//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trxTenagaAhliTMP
    {
        public int IdTenagaAhli { get; set; }
        public Guid GuidHeader { get; set; }
        public System.Guid IdRekanan { get; set; }
        public string NamaLengkap { get; set; }
        public string Jabatan { get; set; }
        public Nullable<int> MulaiMendudukiJabatan { get; set; }
        public Nullable<int> MulaiBekerjaSebagaiPenilai { get; set; }
        public string RiwayatPekerjaan { get; set; }
        public string LingkupPekerjaan { get; set; }
        public string AlumniPTNPTS { get; set; }
        public string JenjangPendidikan { get; set; }
        public string KeanggotaanMAPPI { get; set; }
        public string NoIjinPenilai { get; set; }
        public string KantorPusatCabang { get; set; }
        public string Catatan { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
