//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TrxTenagaAhliUpload
    {
        public int IdTAUpload { get; set; }
        public System.Guid IdRekanan { get; set; }
        public System.DateTime PeriodeBerlaku { get; set; }
        public string Catatan { get; set; }
        public Nullable<System.Guid> ImageBaseName { get; set; }
        public string FileExt { get; set; }
        public System.DateTime LMDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
