//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;    
    public partial class mstRekananForm
    {
        public System.Guid IdRekanan { get; set; }
        public int IdRegion { get; set; }
        public string RegistrationNumber { get; set; }
        public int ClassOfRekanan { get; set; }
        public int IdTypeOfRekanan { get; set; }
        public int IdTypeOfBadanUsaha { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> IdWilayah { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string Kota { get; set; }
        public string ZipCode { get; set; }
        public string Phone1_1 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Phone1) && Phone1.Contains("-"))
        //        {
        //            var arrReturn = Phone1.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[0];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Phone1_1 = value;
        //    }
        //}

        public string Phone1_2 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Phone1) && Phone1.Contains("-"))
        //        {
        //            var arrReturn = Phone1.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[1];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Phone1_2 = value;
        //    }
        //}

        public string Phone1 { get; set; }
        public string Phone2_1 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Phone2) && Phone2.Contains("-"))
        //        {
        //            var arrReturn = Phone2.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[0];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Phone2_1 = value;
        //    }

        //}

        public string Phone2_2 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Phone2) && Phone2.Contains("-"))
        //        {
        //            var arrReturn = Phone2.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[1];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Phone2_2 = value;
        //    }

        //}

        public string Phone2 { get; set; }
        public string Phone3_1 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Phone3) && Phone3.Contains("-"))
        //        {
        //            var arrReturn = Phone3.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[0];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Phone3_1 = value;
        //    }
        //}

        public string Phone3_2 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Phone3) && Phone3.Contains("-"))
        //        {
        //            var arrReturn = Phone3.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[1];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Phone3_2 = value;
        //    }
        //}

        public string Phone3 { get; set; }
        public string Fax1_1 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Fax1) && Fax1.Contains("-"))
        //        {
        //            var arrReturn = Fax1.Split('-');
        //            if(arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[0];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Fax1_1 = value;
        //    }
        //}
        public string Fax1_2 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Fax1) && Fax1.Contains("-"))
        //        {
        //            var arrReturn = Fax1.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[1];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Fax1_2 = value;
        //    }

        //}
        public string Fax1 { get; set; }
        public string Fax2_1 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Fax2) && Fax2.Contains("-"))
        //        {
        //            var arrReturn = Fax2.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[0];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Fax2_1 = value;
        //    }
        //}

        public string Fax2_2 { get; set; }
        //{
        //    get
        //    {
        //        string strReturn = string.Empty;
        //        if (!string.IsNullOrEmpty(Fax2) && Fax2.Contains("-"))
        //        {
        //            var arrReturn = Fax2.Split('-');
        //            if (arrReturn.Length == 2)
        //            {
        //                strReturn = arrReturn[1];
        //            }
        //        }
        //        return strReturn;
        //    }
        //    set
        //    {
        //        Fax2_2 = value;
        //    }
        //}

        public string Fax2 { get; set; }
        public string EmailAddress { get; set; }
        public string PenerbitRating { get; set; }
        public string NilaiRating { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte IsActive { get; set; }
        public IEnumerable<mstTypeOfRegion> TypeOfRegionColls { get; set; }
        public IEnumerable<mstTypeOfRekanan> TypeOfRekananColls { get; set; }
        public IEnumerable<mstTypeOfBadanUsaha> TypeOfBadanUsahaColls { get; set; }
        public IEnumerable<mstWilayah> WilayahColls { get; set; }
        public List<SimpleRef> ClassAB { get; set; }
        public List<SimpleRef> ClassABC { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public IEnumerable<mstReference> LbgPemeringkatColls { get; set; }

    }
}
