//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartClient01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class trxNotarisFormNew 
    {
        public IEnumerable<trxNotarisTabular> LstNotaris { get; set; }
        public trxNotarisDetail DetailNotaris { get; set; }
    }
}
