//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace MVCSmartAPI01.Models
{
    using System;
    public partial class AddEditTDraftCaptionForm
    {
        public int IdNotification { get; set; }
        public int IdNotificationContent { get; set; }
        public int IdNotificationDetail { get; set; }
        public string CaptionInfo { get; set; }
        public int IdTipeNotification { get; set; }
        public int IdLevelUrgensi { get; set; }
        public Nullable<int> BelumKirim { get; set; }
        public Guid SubjectTo { get; set; } //dari sisi rekanan
        public IEnumerable<fGetRekananByIdSupervisor_Result> SubjectToColls { get; set; } //dari sisi PCP
        public string SubjectToStr { get; set; }
        public string SubjectFromStr { get; set; }
        public System.Guid SubjectFrom { get; set; }
        public string BodyContent { get; set; }
        public Nullable<System.Guid> Attachment { get; set; }
        public string FileName1 { get; set; }
        public string FileName2 { get; set; }
        public string FileName3 { get; set; }
        public string FileExt1 { get; set; }
        public string FileExt2 { get; set; }
        public string FileExt3 { get; set; }
        public IEnumerable<SimpleRef> TipeNotifikasiColls { get; set; }
        public IEnumerable<SimpleRef> LevelUrgensiColls { get; set; }
        public bool FlagKirim { get; set; }
        public bool IsRekanan { get; set; }
        public bool IsSaluranEmail { get; set; }
        public bool IsSaluranWhatsapp { get; set; }
    }
}
