//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSmartAPI01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;    
    public partial class mstRekananForm
    {
        public System.Guid IdRekanan { get; set; }
        public int IdRegion { get; set; }
        public string RegistrationNumber { get; set; }
        public int ClassOfRekanan { get; set; }
        public int IdTypeOfRekanan { get; set; }
        public int IdTypeOfBadanUsaha { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> IdWilayah { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string Kota { get; set; }
        public string ZipCode { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string EmailAddress { get; set; }
        public string PenerbitRating { get; set; }
        public string NilaiRating { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte IsActive { get; set; }
        public IEnumerable<mstTypeOfRegion> TypeOfRegionColls { get; set; }
        public IEnumerable<mstTypeOfRekanan> TypeOfRekananColls { get; set; }
        public IEnumerable<mstTypeOfBadanUsaha> TypeOfBadanUsahaColls { get; set; }
        public IEnumerable<mstWilayah> WilayahColls { get; set; }
        public List<SimpleRef> ClassAB { get; set; }
        public List<SimpleRef> ClassABC { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
    }
}
